sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-precise
    packages:
      - chefdk

branches:
  only:
  - master

services: docker

env:
  matrix:
  - INSTANCE=default-centos-7
  - INSTANCE=default-debian-8 
  - INSTANCE=default-ubuntu-1604
  - INSTANCE=default-ubuntu-1404
  - INSTANCE=default-ubuntu-1204
  - INSTANCE=cacher-client-ubuntu-1604
  - INSTANCE=cacher-client-ubuntu-1404
  - INSTANCE=cacher-client-ubuntu-1204
  - INSTANCE=cacher-ng-ubuntu-1604
  - INSTANCE=cacher-ng-ubuntu-1404
  - INSTANCE=cacher-ng-ubuntu-1204
  - INSTANCE=cacher-ng-client-ubuntu-1604
  - INSTANCE=cacher-ng-client-ubuntu-1404
  - INSTANCE=cacher-ng-client-ubuntu-1204
  - INSTANCE=compile-time-ubuntu-1604
  - INSTANCE=compile-time-ubuntu-1404
  - INSTANCE=compile-time-ubuntu-1204
  - INSTANCE=lwrps-ubuntu-1604
  - INSTANCE=lwrps-ubuntu-1404
  - INSTANCE=lwrps-ubuntu-1204
  - INSTANCE=unattended-upgrades-ubuntu-1604
  - INSTANCE=unattended-upgrades-ubuntu-1404
  - INSTANCE=unattended-upgrades-ubuntu-1204

  fast_finish: true

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-dokken

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/cookstyle
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any -P
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
